version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/backend"
    schedule:
      interval: "daily"
  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: daily
      time: "10:00"
    versioning-strategy: increase
