#!/usr/bin/env bash

# bootstrap.sh
#
# Please use this script to install common environmen.
# It will install system-specific packages and other stuff.
# Run as:
#   > [sudo] ./bootstrap

debian_packages=(
  mongodb nodejs-legacy npm
  build-essential
  )

check_core_componenta_availability ()
{
  local components=(git ruby mongod)
  for component in ${components[*]}; do
    type $component >/dev/null 2>&1
    case $? in
      0) echo "OK: $component already installed" ;;
      *) echo "Please install $component" && exit 1 ;;
    esac
  done
}

install_ubuntu_packages ()
{
  case `whoami` in
    root)
      for package in ${debian_packages[*]}; do
        apt-get install --force-yes -y $package
      done
      ;;
    *) echo "Run this as root" && exit 1 ;;
  esac
}


install_system_specific_packages ()
{
  local _uname=`uname -a`
  if [[ $_uname =~ "Debian" ]]; then local sys="debian"; fi
  if [[ $_uname =~ "Ubuntu" ]]; then local sys="ubuntu"; fi

  case $sys in
    ubuntu) install_ubuntu_packages ;;
    debian) install_ubuntu_packages ;;
    *)
      echo "Sorry - no installation scenario for your system."
      echo "Use Ubuntu or Debian."
      exit 1
  esac
}


project_preparation ()
{
  bundle install
  npm install -g bower
  bower install
  mkdir -p log
}

# Execution
# ---------

check_core_componenta_availability
install_system_specific_packages
project_preparation
