# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activesupport'

gem 'puma'
gem 'rack'
gem 'rackup'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-subdomain'

gem 'mongoid'
gem 'mongoid-suicide'

group :development do
  gem 'pry'
  gem 'racksh'
end

group :test do
  gem 'capybara'
  gem 'rspec'
  gem 'selenium-webdriver'
end
